[package]
name = "persistent_hook"
version = "0.1.0"
authors = ["galtashma <galtashma@gmail.com>"]
edition = "2018"

[lib]
name         = "persistent"
crate-type   = ["rlib", "cdylib"]


[dependencies]
